apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{APP_NAME}}
spec:
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - name: {{APP_NAME}}
          image: {{IMAGE_NAME}}
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
      serviceAccountName: {{APP_NAME}}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{APP_NAME}}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["list"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{APP_NAME}}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{APP_NAME}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{APP_NAME}}
subjects:
- kind: ServiceAccount
  name: {{APP_NAME}}
  namespace: default
